name: Kwiki-Theme-JustContent
version: 0.10
abstract: The Kwiki theme that renders only conent pane
author: Kang-min Liu <gugod@gugod.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.38
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
